Dev
svinstech/slack-notifier-orb pull request #25
Opened 2023-09-21 15:15 UTC by KellenKincaid

2023-09-25 17:53 UTC, snowinferno commented
I'm not overly familiar with ORB best practices, but from a node/typescript standpoint it's typically bad practice to commit `node_modules`. `yarn.lock` will cause the same version of the packages to be installed when running `yarn install` with some exceptions I won't detail here. In CI environments, `yarn install --frozen-lockfile` will strictly honor the lock file without updating any versions.

If node modules need to be installed for parts of the CI process, there should be a predicate step or command that runs `yarn install --frozen-lockfile` to install the node dependencies before any step or command that tries to use them.

2023-09-25 19:48 UTC, snowinferno requested changes
TL;DR of my comments:

1. use `yarn install --frozen-lockfile`. There have been times when a module developer releases a breaking change in a _**patch version**_ which `yarn` and `yarn install` will install given the entries in the `package.json`.
2. Unless there is a compelling reason to commit `node_modules`, add `node_modules` to `.gitignore` and delete `node_modules` from the repo. It makes the repo unnecessarily large and adds noise to PRs any time there is a change in dependencies.

Nitpicks, not requiring the below changes for approval:

By default, the environment gets loaded into `process.env` and can be read from there. No matter what the env variable is it will be provided on `process.env` as a string. Assigning values into `process.env` will convert any value to a string. This may reduce the number of arguments being supplied to the TS functions if it's just passing in values that are also on the environment. By default `execSync` provides the same values from `process.env` to the new child process.

File I/O can be done all within node without having to spawn a new process and spin up a new bash shell to execute the bash script. Node built-in I/O is done on a protected separate thread which uses OS interfaces to perform the I/O. Having said that, I don't think there is significant difference in performance whether node built-in I/O is used or a new process is spawned to do the I/O through bash.

2023-09-27 16:07 UTC, KellenKincaid commented on src/examples/example.yml
> +        - image: cimg/base:current
Good catch.
Changed `cimg/base:current` to `cimg/node:current` where appropriate.

2023-09-27 16:09 UTC, KellenKincaid commented on .gitignore
> +**/dist
Big brain fart.
Removed `node_modules` from the remote repo and added it to the `.gitignore`.

2023-09-27 20:38 UTC, snowinferno commented on src/scripts/slack_id_lookup_table_scripts/lookup_table_functions.ts
> +async function AddUserDataToLookupTable(_lookupTable:string[], _writeLookupTableShellScriptFilePath:string, _lookupTableFilePath:string, _slackUserInfoFilePath:string) {
How important is it to wait for `readFile` to finish reading the file in and `exec` to finish writing the file back out before anything else happens in the code that calls this?

As it stands, the code calling this method will continue without waiting for the file to be fully read and without waiting for the `exec` call to finish.

There are a few options depending on which asynchronous activities need to be completed before continuing code execution.

2023-09-28 19:40 UTC, snowinferno approved these changes
Looks good to me!

I left a couple of recommendations but I don't think they need to hold up approval.

2023-09-28 19:40 UTC, snowinferno commented on src/scripts/slack_id_lookup_table_scripts/generate_slack_id_lookup_table.sh
> +mkdir "${SLACK_DATA_DIRECTORY_PATH}"
If a user is allowed to specify a deep path, say something like `tmp/some/folder/slackData`, `mkdir -p` would make sure the full path is created if any segments of the path are missing.

2023-09-28 19:40 UTC, snowinferno commented on src/scripts/slack_id_lookup_table_scripts/lookup_table_functions.ts
> +    WriteLookupTableToFile(_lookupTable, _writeLookupTableShellScriptFilePath, _lookupTableFilePath);
A try/catch block is recommended here in case there are any errors reading the file, parsing the JSON, or executing the bash script to write the file. Without catching the exception, the process will exit out with an `UncaughtErrorException` detailing the uncaught error.

Alternatively a try/catch block can be put around each call to `readFileSync`, `JSON.parse`, and `execSync` calls to get finer control of error output.

```suggestion
    try {
        AddUserDataToLookupTable(_lookupTable, _slackUserInfoFilePath);
        AddUserGroupDataToLookupTable(_lookupTable, _slackGroupInfoFilePath);
        WriteLookupTableToFile(_lookupTable, _writeLookupTableShellScriptFilePath, _lookupTableFilePath);
    } catch (e) {
        console.error('Something went wrong!', e);
    }
```

2023-09-28 20:14 UTC, snowinferno approved these changes

2023-09-28 20:30 UTC, KellenKincaid commented on src/scripts/slack_id_lookup_table_scripts/generate_slack_id_lookup_table.sh
> +mkdir "${SLACK_DATA_DIRECTORY_PATH}"
Ahh good to know! I'll add this change in a future PR

2023-09-28 20:31 UTC, KellenKincaid commented on src/scripts/slack_id_lookup_table_scripts/lookup_table_functions.ts
> +    WriteLookupTableToFile(_lookupTable, _writeLookupTableShellScriptFilePath, _lookupTableFilePath);
Great idea, I'll add a try-catch block to each critical point with a detailed error message.

2023-09-28 20:31 UTC, merged